
--DESATIVAR IDENTITY TABELA
SET IDENTITY_INSERT Marca ON

Insert Into Marca (Id, Nome) Values (1,'CHEVROLET')
Insert Into Marca (Id, Nome) Values (2,'VOLKSWAGEN')
Insert Into Marca (Id, Nome) Values (3,'FIAT')
Insert Into Marca (Id, Nome) Values (4,'MERCEDES-BENZ')
Insert Into Marca (Id, Nome) Values (5,'CITROEN')
Insert Into Marca (Id, Nome) Values (6,'CHANA')
Insert Into Marca (Id, Nome) Values (7,'HONDA')
Insert Into Marca (Id, Nome) Values (8,'SUBARU')
Insert Into Marca (Id, Nome) Values (10,'FERRARI')
Insert Into Marca (Id, Nome) Values (11,'BUGATTI')
Insert Into Marca (Id, Nome) Values (12,'LAMBORGHINI')
Insert Into Marca (Id, Nome) Values (13,'FORD')
Insert Into Marca (Id, Nome) Values (14,'HYUNDAI')
Insert Into Marca (Id, Nome) Values (15,'JAC')
Insert Into Marca (Id, Nome) Values (16,'KIA')
Insert Into Marca (Id, Nome) Values (17,'GURGEL')
Insert Into Marca (Id, Nome) Values (18,'DODGE')
Insert Into Marca (Id, Nome) Values (19,'CHRYSLER')
Insert Into Marca (Id, Nome) Values (20,'BENTLEY')
Insert Into Marca (Id, Nome) Values (21,'SSANGYONG')
Insert Into Marca (Id, Nome) Values (22,'PEUGEOT')
Insert Into Marca (Id, Nome) Values (23,'TOYOTA')
Insert Into Marca (Id, Nome) Values (24,'RENAULT')
Insert Into Marca (Id, Nome) Values (25,'ACURA')
Insert Into Marca (Id, Nome) Values (26,'ADAMO')
Insert Into Marca (Id, Nome) Values (27,'AGRALE')
Insert Into Marca (Id, Nome) Values (28,'ALFA ROMEO')
Insert Into Marca (Id, Nome) Values (29,'AMERICAR')
Insert Into Marca (Id, Nome) Values (31,'ASTON MARTIN')
Insert Into Marca (Id, Nome) Values (32,'AUDI')
Insert Into Marca (Id, Nome) Values (34,'BEACH')
Insert Into Marca (Id, Nome) Values (35,'BIANCO')
Insert Into Marca (Id, Nome) Values (36,'BMW')
Insert Into Marca (Id, Nome) Values (37,'BORGWARD')
Insert Into Marca (Id, Nome) Values (38,'BRILLIANCE')
Insert Into Marca (Id, Nome) Values (41,'BUICK')
Insert Into Marca (Id, Nome) Values (42,'CBT')
Insert Into Marca (Id, Nome) Values (43,'NISSAN')
Insert Into Marca (Id, Nome) Values (44,'CHAMONIX')
Insert Into Marca (Id, Nome) Values (46,'CHEDA')
Insert Into Marca (Id, Nome) Values (47,'CHERY')
Insert Into Marca (Id, Nome) Values (48,'CORD')
Insert Into Marca (Id, Nome) Values (49,'COYOTE')
Insert Into Marca (Id, Nome) Values (50,'CROSS LANDER')
Insert Into Marca (Id, Nome) Values (51,'DAEWOO')
Insert Into Marca (Id, Nome) Values (52,'DAIHATSU')
Insert Into Marca (Id, Nome) Values (53,'VOLVO')
Insert Into Marca (Id, Nome) Values (54,'DE SOTO')
Insert Into Marca (Id, Nome) Values (55,'DETOMAZO')
Insert Into Marca (Id, Nome) Values (56,'DELOREAN')
Insert Into Marca (Id, Nome) Values (57,'DKW-VEMAG')
Insert Into Marca (Id, Nome) Values (59,'SUZUKI')
Insert Into Marca (Id, Nome) Values (60,'EAGLE')
Insert Into Marca (Id, Nome) Values (61,'EFFA')
Insert Into Marca (Id, Nome) Values (63,'ENGESA')
Insert Into Marca (Id, Nome) Values (64,'ENVEMO')
Insert Into Marca (Id, Nome) Values (65,'FARUS')
Insert Into Marca (Id, Nome) Values (66,'FERCAR')
Insert Into Marca (Id, Nome) Values (68,'FNM')
Insert Into Marca (Id, Nome) Values (69,'PONTIAC')
Insert Into Marca (Id, Nome) Values (70,'PORSCHE')
Insert Into Marca (Id, Nome) Values (72,'GEO')
Insert Into Marca (Id, Nome) Values (74,'GRANCAR')
Insert Into Marca (Id, Nome) Values (75,'GREAT WALL')
Insert Into Marca (Id, Nome) Values (76,'HAFEI')
Insert Into Marca (Id, Nome) Values (78,'HOFSTETTER')
Insert Into Marca (Id, Nome) Values (79,'HUDSON')
Insert Into Marca (Id, Nome) Values (80,'HUMMER')
Insert Into Marca (Id, Nome) Values (82,'INFINITI')
Insert Into Marca (Id, Nome) Values (83,'INTERNATIONAL')
Insert Into Marca (Id, Nome) Values (86,'JAGUAR')
Insert Into Marca (Id, Nome) Values (87,'JEEP')
Insert Into Marca (Id, Nome) Values (88,'JINBEI')
Insert Into Marca (Id, Nome) Values (89,'JPX')
Insert Into Marca (Id, Nome) Values (90,'KAISER')
Insert Into Marca (Id, Nome) Values (91,'KOENIGSEGG')
Insert Into Marca (Id, Nome) Values (92,'LAUTOMOBILE')
Insert Into Marca (Id, Nome) Values (93,'LAUTOCRAFT')
Insert Into Marca (Id, Nome) Values (94,'LADA')
Insert Into Marca (Id, Nome) Values (95,'LANCIA')
Insert Into Marca (Id, Nome) Values (96,'LAND ROVER')
Insert Into Marca (Id, Nome) Values (97,'LEXUS')
Insert Into Marca (Id, Nome) Values (98,'LIFAN')
Insert Into Marca (Id, Nome) Values (99,'LINCOLN')
Insert Into Marca (Id, Nome) Values (100,'LOBINI')
Insert Into Marca (Id, Nome) Values (101,'LOTUS')
Insert Into Marca (Id, Nome) Values (102,'MAHINDRA')
Insert Into Marca (Id, Nome) Values (104,'MASERATI')
Insert Into Marca (Id, Nome) Values (106,'MATRA')
Insert Into Marca (Id, Nome) Values (107,'MAYBACH')
Insert Into Marca (Id, Nome) Values (108,'MAZDA')
Insert Into Marca (Id, Nome) Values (109,'MENON')
Insert Into Marca (Id, Nome) Values (110,'MERCURY')
Insert Into Marca (Id, Nome) Values (111,'MITSUBISHI')
Insert Into Marca (Id, Nome) Values (112,'MG')
Insert Into Marca (Id, Nome) Values (113,'MINI')
Insert Into Marca (Id, Nome) Values (114,'MIURA')
Insert Into Marca (Id, Nome) Values (115,'MORRIS')
Insert Into Marca (Id, Nome) Values (116,'MP LAFER')
Insert Into Marca (Id, Nome) Values (117,'MPLM')
Insert Into Marca (Id, Nome) Values (118,'NEWTRACK')
Insert Into Marca (Id, Nome) Values (119,'NISSIN')
Insert Into Marca (Id, Nome) Values (120,'OLDSMOBILE')
Insert Into Marca (Id, Nome) Values (121,'PAG')
Insert Into Marca (Id, Nome) Values (122,'PAGANI')
Insert Into Marca (Id, Nome) Values (123,'PLYMOUTH')
Insert Into Marca (Id, Nome) Values (124,'PUMA')
Insert Into Marca (Id, Nome) Values (125,'RENO')
Insert Into Marca (Id, Nome) Values (126,'REVA-I')
Insert Into Marca (Id, Nome) Values (127,'ROLLS-ROYCE')
Insert Into Marca (Id, Nome) Values (129,'ROMI')
Insert Into Marca (Id, Nome) Values (130,'SEAT')
Insert Into Marca (Id, Nome) Values (131,'UTILITARIOS AGRICOLAS')
Insert Into Marca (Id, Nome) Values (132,'SHINERAY')
Insert Into Marca (Id, Nome) Values (137,'SAAB')
Insert Into Marca (Id, Nome) Values (139,'SHORT')
Insert Into Marca (Id, Nome) Values (141,'SIMCA')
Insert Into Marca (Id, Nome) Values (142,'SMART')
Insert Into Marca (Id, Nome) Values (143,'SPYKER')
Insert Into Marca (Id, Nome) Values (144,'STANDARD')
Insert Into Marca (Id, Nome) Values (145,'STUDEBAKER')
Insert Into Marca (Id, Nome) Values (146,'TAC')
Insert Into Marca (Id, Nome) Values (147,'TANGER')
Insert Into Marca (Id, Nome) Values (148,'TRIUMPH')
Insert Into Marca (Id, Nome) Values (149,'TROLLER')
Insert Into Marca (Id, Nome) Values (150,'UNIMOG')
Insert Into Marca (Id, Nome) Values (154,'WIESMANN')
Insert Into Marca (Id, Nome) Values (155,'CADILLAC')
Insert Into Marca (Id, Nome) Values (156,'AM GEN')
Insert Into Marca (Id, Nome) Values (157,'BUGGY')
Insert Into Marca (Id, Nome) Values (158,'WILLYS OVERLAND')
Insert Into Marca (Id, Nome) Values (161,'KASEA')
Insert Into Marca (Id, Nome) Values (162,'SATURN')
Insert Into Marca (Id, Nome) Values (163,'SWELL MINI')
Insert Into Marca (Id, Nome) Values (175,'SKODA')
Insert Into Marca (Id, Nome) Values (239,'KARMANN GHIA')
Insert Into Marca (Id, Nome) Values (254,'KART')
Insert Into Marca (Id, Nome) Values (258,'HANOMAG')
Insert Into Marca (Id, Nome) Values (261,'OUTROS')
Insert Into Marca (Id, Nome) Values (265,'HILLMAN')
Insert Into Marca (Id, Nome) Values (288,'HRG')
Insert Into Marca (Id, Nome) Values (295,'GAIOLA')
Insert Into Marca (Id, Nome) Values (338,'TATA')
Insert Into Marca (Id, Nome) Values (341,'DITALLY')
Insert Into Marca (Id, Nome) Values (345,'RELY')
Insert Into Marca (Id, Nome) Values (346,'MCLAREN')
Insert Into Marca (Id, Nome) Values (534,'GEELY')

--ATIVAR IDENTITY TABELA
SET IDENTITY_INSERT Marca OFF