--DESATIVAR IDENTITY TABELA
SET IDENTITY_INSERT Modelo ON

Insert Into Modelo (Id, Nome, MarcaId) Values (1,'INTEGRA',25)
Insert Into Modelo (Id, Nome, MarcaId) Values (2,'LEGEND',25)
Insert Into Modelo (Id, Nome, MarcaId) Values (3,'NSX',25)
Insert Into Modelo (Id, Nome, MarcaId) Values (4,'MARRUA',27)
Insert Into Modelo (Id, Nome, MarcaId) Values (5,'145',28)
Insert Into Modelo (Id, Nome, MarcaId) Values (6,'147',28)
Insert Into Modelo (Id, Nome, MarcaId) Values (7,'155',28)
Insert Into Modelo (Id, Nome, MarcaId) Values (8,'156',28)
Insert Into Modelo (Id, Nome, MarcaId) Values (9,'164',28)
Insert Into Modelo (Id, Nome, MarcaId) Values (10,'166',28)
Insert Into Modelo (Id, Nome, MarcaId) Values (11,'2300',28)
Insert Into Modelo (Id, Nome, MarcaId) Values (12,'SPIDER',28)
Insert Into Modelo (Id, Nome, MarcaId) Values (13,'HUMMER',156)
Insert Into Modelo (Id, Nome, MarcaId) Values (14,'AM-825',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (15,'HI-TOPIC',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (16,'ROCSTA',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (17,'TOPIC',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (18,'TOWNER',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (19,'100',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (20,'80',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (21,'A1',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (22,'A3',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (23,'A4 SEDAN',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (24,'A5 COUPE',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (25,'A6 SEDAN',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (26,'A7',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (27,'A8',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (30,'Q3',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (31,'Q5',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (32,'Q7',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (33,'R8',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (34,'RS3',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (35,'RS4',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (36,'RS5',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (37,'RS6',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (38,'S3',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (39,'S4 SEDAN',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (40,'S6 SEDAN',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (41,'S8',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (42,'TT',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (43,'TTS',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (86,'BUGGY',157)
Insert Into Modelo (Id, Nome, MarcaId) Values (87,'DEVILLE',155)
Insert Into Modelo (Id, Nome, MarcaId) Values (88,'ELDORADO',155)
Insert Into Modelo (Id, Nome, MarcaId) Values (89,'SEVILLE',155)
Insert Into Modelo (Id, Nome, MarcaId) Values (90,'JAVALI',42)
Insert Into Modelo (Id, Nome, MarcaId) Values (92,'MINI STAR FAMILY',6)
Insert Into Modelo (Id, Nome, MarcaId) Values (93,'MINI STAR UTILITY',6)
Insert Into Modelo (Id, Nome, MarcaId) Values (95,'CIELO',47)
Insert Into Modelo (Id, Nome, MarcaId) Values (96,'FACE',47)
Insert Into Modelo (Id, Nome, MarcaId) Values (97,'QQ',47)
Insert Into Modelo (Id, Nome, MarcaId) Values (98,'S-18',47)
Insert Into Modelo (Id, Nome, MarcaId) Values (99,'TIGGO',47)
Insert Into Modelo (Id, Nome, MarcaId) Values (100,'300C',19)
Insert Into Modelo (Id, Nome, MarcaId) Values (101,'CARAVAN',19)
Insert Into Modelo (Id, Nome, MarcaId) Values (102,'CIRRUS',19)
Insert Into Modelo (Id, Nome, MarcaId) Values (103,'GRAN CARAVAN',19)
Insert Into Modelo (Id, Nome, MarcaId) Values (104,'LE BARON',19)
Insert Into Modelo (Id, Nome, MarcaId) Values (105,'NEON',19)
Insert Into Modelo (Id, Nome, MarcaId) Values (106,'PT CRUISER',19)
Insert Into Modelo (Id, Nome, MarcaId) Values (107,'SEBRING',19)
Insert Into Modelo (Id, Nome, MarcaId) Values (108,'STRATUS',19)
Insert Into Modelo (Id, Nome, MarcaId) Values (109,'TOWN E COUNTRY',19)
Insert Into Modelo (Id, Nome, MarcaId) Values (110,'VISION',19)
Insert Into Modelo (Id, Nome, MarcaId) Values (111,'AIRCROSS',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (112,'AX',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (113,'BERLINGO',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (114,'BX',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (115,'C3',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (116,'C4',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (117,'C5',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (118,'C6',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (119,'C8',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (120,'DS3',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (121,'EVASION',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (122,'JUMPER',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (123,'XANTIA',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (124,'XM',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (125,'XSARA',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (126,'ZX',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (127,'CL-244',50)
Insert Into Modelo (Id, Nome, MarcaId) Values (128,'CL-330',50)
Insert Into Modelo (Id, Nome, MarcaId) Values (129,'ESPERO',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (130,'LANOS',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (131,'LEGANZA',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (132,'NUBIRA',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (133,'PRINCE',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (134,'RACER',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (135,'SUPER SALON',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (136,'TICO',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (137,'APPLAUSE',52)
Insert Into Modelo (Id, Nome, MarcaId) Values (138,'CHARADE',52)
Insert Into Modelo (Id, Nome, MarcaId) Values (139,'CUORE',52)
Insert Into Modelo (Id, Nome, MarcaId) Values (140,'FEROZA',52)
Insert Into Modelo (Id, Nome, MarcaId) Values (141,'GRAN MOVE',52)
Insert Into Modelo (Id, Nome, MarcaId) Values (142,'MOVE VAN',52)
Insert Into Modelo (Id, Nome, MarcaId) Values (143,'TERIOS',52)
Insert Into Modelo (Id, Nome, MarcaId) Values (144,'AVENGER',18)
Insert Into Modelo (Id, Nome, MarcaId) Values (145,'DAKOTA',18)
Insert Into Modelo (Id, Nome, MarcaId) Values (146,'JOURNEY',18)
Insert Into Modelo (Id, Nome, MarcaId) Values (147,'RAM',18)
Insert Into Modelo (Id, Nome, MarcaId) Values (148,'STEALTH',18)
Insert Into Modelo (Id, Nome, MarcaId) Values (151,'M-100',61)
Insert Into Modelo (Id, Nome, MarcaId) Values (152,'PLUTUS',61)
Insert Into Modelo (Id, Nome, MarcaId) Values (153,'START',61)
Insert Into Modelo (Id, Nome, MarcaId) Values (155,'ULC',61)
Insert Into Modelo (Id, Nome, MarcaId) Values (158,'ENGESA',63)
Insert Into Modelo (Id, Nome, MarcaId) Values (159,'CAMPER',64)
Insert Into Modelo (Id, Nome, MarcaId) Values (160,'MASTER',64)
Insert Into Modelo (Id, Nome, MarcaId) Values (161,'348',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (162,'355',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (163,'360',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (164,'456',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (165,'550',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (166,'575M',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (167,'612',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (168,'CALIFORNIA',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (169,'F430',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (170,'F599',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (171,'147',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (174,'500',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (175,'BRAVA',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (176,'BRAVO',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (178,'COUPE',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (179,'DOBLO',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (180,'DUCATO CARGO',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (181,'DUNA',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (182,'ELBA',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (183,'FIORINO',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (184,'FREEMONT',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (185,'GRAND SIENA',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (186,'IDEA',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (187,'LINEA',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (188,'MAREA',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (189,'OGGI',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (190,'PALIO',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (191,'PANORAMA',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (192,'PREMIO',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (193,'PUNTO',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (194,'SIENA',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (195,'STILO',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (196,'STRADA',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (197,'TEMPRA',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (198,'TIPO',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (199,'UNO',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (201,'AEROSTAR',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (202,'ASPIRE',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (203,'BELINA',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (204,'CLUB WAGON',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (205,'CONTOUR',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (206,'CORCEL II',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (207,'COURIER',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (208,'CROWN VICTORIA',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (209,'DEL REY',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (210,'ECOSPORT',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (211,'EDGE',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (212,'ESCORT',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (213,'EXPEDITION',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (214,'EXPLORER',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (215,'F-100',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (216,'F-1000',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (217,'F-150',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (218,'F-250',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (219,'FIESTA',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (220,'FOCUS',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (221,'FURGLAINE',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (222,'FUSION',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (223,'IBIZA',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (224,'KA',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (225,'MONDEO',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (226,'MUSTANG',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (227,'PAMPA',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (228,'PROBE',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (229,'RANGER',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (230,'VERSAILLES ROYALE',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (231,'TAURUS',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (232,'THUNDERBIRD',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (233,'TRANSIT',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (234,'VERONA',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (235,'VERSAILLES',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (236,'WINDSTAR',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (238,'A-10',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (239,'A-20',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (240,'AGILE',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (241,'ASTRA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (242,'BLAZER',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (243,'BONANZA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (245,'C-10',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (246,'C-20',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (247,'CALIBRA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (248,'CAMARO',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (249,'CAPRICE',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (250,'CAPTIVA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (251,'CARAVAN',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (252,'CAVALIER',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (253,'CELTA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (255,'CHEVY',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (256,'CHEYNNE',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (258,'COBALT',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (259,'CORSA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (262,'CORVETTE',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (263,'CRUZE',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (264,'D-10',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (265,'D-20',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (266,'IPANEMA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (267,'KADETT',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (268,'LUMINA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (269,'MALIBU',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (271,'MERIVA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (272,'MONTANA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (274,'OMEGA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (275,'OPALA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (276,'PRISMA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (277,'S10',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (280,'SILVERADO',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (281,'SONIC',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (282,'SONOMA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (283,'SPACEVAN',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (284,'SS10',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (285,'SUBURBAN',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (287,'SYCLONE',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (288,'TIGRA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (289,'TRACKER',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (290,'TRAFIC',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (291,'VECTRA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (292,'VERANEIO',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (293,'ZAFIRA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (294,'HOVER',75)
Insert Into Modelo (Id, Nome, MarcaId) Values (295,'BR-800',17)
Insert Into Modelo (Id, Nome, MarcaId) Values (296,'CARAJAS',17)
Insert Into Modelo (Id, Nome, MarcaId) Values (297,'TOCANTINS',17)
Insert Into Modelo (Id, Nome, MarcaId) Values (298,'XAVANTE',17)
Insert Into Modelo (Id, Nome, MarcaId) Values (299,'VIP',17)
Insert Into Modelo (Id, Nome, MarcaId) Values (300,'TOWNER',76)
Insert Into Modelo (Id, Nome, MarcaId) Values (301,'ACCORD',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (302,'CITY',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (303,'CIVIC',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (304,'CR-V',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (305,'FIT',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (306,'ODYSSEY',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (307,'PASSPORT',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (308,'PRELUDE',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (309,'ACCENT',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (310,'ATOS',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (311,'AZERA',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (312,'COUPE',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (314,'ELANTRA',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (315,'EXCEL',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (316,'GALLOPER',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (317,'GENESIS',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (318,'H1',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (319,'H100',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (321,'I30',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (323,'IX35',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (324,'MATRIX',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (325,'PORTER',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (326,'SANTA FE',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (327,'SCOUPE',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (328,'SONATA',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (329,'TERRACAN',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (330,'TRAJET',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (331,'TUCSON',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (332,'VELOSTER',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (333,'VERACRUZ',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (334,'AMIGO',84)
Insert Into Modelo (Id, Nome, MarcaId) Values (335,'HOMBRE',84)
Insert Into Modelo (Id, Nome, MarcaId) Values (336,'RODEO',84)
Insert Into Modelo (Id, Nome, MarcaId) Values (337,'J3',15)
Insert Into Modelo (Id, Nome, MarcaId) Values (338,'J5',15)
Insert Into Modelo (Id, Nome, MarcaId) Values (339,'J6',15)
Insert Into Modelo (Id, Nome, MarcaId) Values (340,'DAIMLER',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (341,'S-TYPE',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (342,'X-TYPE',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (345,'MODELOS XJ',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (352,'MODELOS XK',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (354,'CHEROKEE',87)
Insert Into Modelo (Id, Nome, MarcaId) Values (355,'COMMANDER',87)
Insert Into Modelo (Id, Nome, MarcaId) Values (356,'COMPASS',87)
Insert Into Modelo (Id, Nome, MarcaId) Values (357,'GRAND CHEROKEE',87)
Insert Into Modelo (Id, Nome, MarcaId) Values (358,'WRANGLER',87)
Insert Into Modelo (Id, Nome, MarcaId) Values (359,'TOPIC VAN',88)
Insert Into Modelo (Id, Nome, MarcaId) Values (360,'JIPE MONTEZ',89)
Insert Into Modelo (Id, Nome, MarcaId) Values (361,'PICAPE MONTEZ',89)
Insert Into Modelo (Id, Nome, MarcaId) Values (362,'BESTA',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (363,'BONGO',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (364,'CADENZA',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (365,'CARENS',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (366,'CARNIVAL',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (367,'CERATO',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (368,'CERES',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (369,'CLARUS',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (370,'MAGENTIS',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (371,'MOHAVE',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (372,'OPIRUS',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (373,'OPTIMA',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (374,'PICANTO',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (375,'SEPHIA',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (376,'SHUMA',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (377,'SORENTO',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (378,'SOUL',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (379,'SPORTAGE',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (380,'LAIKA',94)
Insert Into Modelo (Id, Nome, MarcaId) Values (381,'NIVA',94)
Insert Into Modelo (Id, Nome, MarcaId) Values (382,'SAMARA',94)
Insert Into Modelo (Id, Nome, MarcaId) Values (383,'GALLARDO',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (384,'MURCIELAGO',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (385,'DEFENDER',96)
Insert Into Modelo (Id, Nome, MarcaId) Values (386,'DISCOVERY',96)
Insert Into Modelo (Id, Nome, MarcaId) Values (389,'FREELANDER',96)
Insert Into Modelo (Id, Nome, MarcaId) Values (391,'NEW RANGE',96)
Insert Into Modelo (Id, Nome, MarcaId) Values (392,'RANGE ROVER',96)
Insert Into Modelo (Id, Nome, MarcaId) Values (393,'ES',97)
Insert Into Modelo (Id, Nome, MarcaId) Values (396,'GS',97)
Insert Into Modelo (Id, Nome, MarcaId) Values (397,'IS-300',97)
Insert Into Modelo (Id, Nome, MarcaId) Values (398,'LS',97)
Insert Into Modelo (Id, Nome, MarcaId) Values (400,'RX',97)
Insert Into Modelo (Id, Nome, MarcaId) Values (402,'SC',97)
Insert Into Modelo (Id, Nome, MarcaId) Values (403,'320',98)
Insert Into Modelo (Id, Nome, MarcaId) Values (404,'620',98)
Insert Into Modelo (Id, Nome, MarcaId) Values (405,'H1',100)
Insert Into Modelo (Id, Nome, MarcaId) Values (406,'ELAN',101)
Insert Into Modelo (Id, Nome, MarcaId) Values (407,'ESPRIT',101)
Insert Into Modelo (Id, Nome, MarcaId) Values (408,'SCORPIO',102)
Insert Into Modelo (Id, Nome, MarcaId) Values (409,'222',104)
Insert Into Modelo (Id, Nome, MarcaId) Values (410,'228',104)
Insert Into Modelo (Id, Nome, MarcaId) Values (411,'3200',104)
Insert Into Modelo (Id, Nome, MarcaId) Values (412,'430',104)
Insert Into Modelo (Id, Nome, MarcaId) Values (413,'COUPE',104)
Insert Into Modelo (Id, Nome, MarcaId) Values (414,'GHIBLI',104)
Insert Into Modelo (Id, Nome, MarcaId) Values (415,'GRANCABRIO',104)
Insert Into Modelo (Id, Nome, MarcaId) Values (416,'GRANSPORT',104)
Insert Into Modelo (Id, Nome, MarcaId) Values (417,'GRANTURISMO',104)
Insert Into Modelo (Id, Nome, MarcaId) Values (418,'QUATTROPORTE',104)
Insert Into Modelo (Id, Nome, MarcaId) Values (419,'SHAMAL',104)
Insert Into Modelo (Id, Nome, MarcaId) Values (420,'SPIDER',104)
Insert Into Modelo (Id, Nome, MarcaId) Values (422,'PICK-UP',106)
Insert Into Modelo (Id, Nome, MarcaId) Values (423,'323',108)
Insert Into Modelo (Id, Nome, MarcaId) Values (424,'626',108)
Insert Into Modelo (Id, Nome, MarcaId) Values (425,'929',108)
Insert Into Modelo (Id, Nome, MarcaId) Values (426,'B-2500',108)
Insert Into Modelo (Id, Nome, MarcaId) Values (427,'B2200',108)
Insert Into Modelo (Id, Nome, MarcaId) Values (428,'MILLENIA',108)
Insert Into Modelo (Id, Nome, MarcaId) Values (429,'MPV',108)
Insert Into Modelo (Id, Nome, MarcaId) Values (430,'MX-3',108)
Insert Into Modelo (Id, Nome, MarcaId) Values (431,'MX-5',108)
Insert Into Modelo (Id, Nome, MarcaId) Values (432,'NAVAJO',108)
Insert Into Modelo (Id, Nome, MarcaId) Values (433,'PROTEGE',108)
Insert Into Modelo (Id, Nome, MarcaId) Values (434,'RX',108)
Insert Into Modelo (Id, Nome, MarcaId) Values (467,'CLASSE A',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (468,'CLASSE B',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (469,'CLASSE R',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (498,'CLASSE GLK',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (531,'SPRINTER',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (532,'MYSTIQUE',110)
Insert Into Modelo (Id, Nome, MarcaId) Values (533,'SABLE',110)
Insert Into Modelo (Id, Nome, MarcaId) Values (534,'550',112)
Insert Into Modelo (Id, Nome, MarcaId) Values (535,'MG6',112)
Insert Into Modelo (Id, Nome, MarcaId) Values (536,'COOPER',113)
Insert Into Modelo (Id, Nome, MarcaId) Values (537,'ONE',113)
Insert Into Modelo (Id, Nome, MarcaId) Values (538,'3000',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (539,'AIRTREK',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (540,'ASX',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (541,'COLT',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (542,'DIAMANT',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (543,'ECLIPSE',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (544,'EXPO',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (545,'GALANT',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (546,'GRANDIS',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (547,'L200',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (548,'L300',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (549,'LANCER',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (550,'MIRAGE',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (551,'MONTERO',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (552,'OUTLANDER',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (553,'PAJERO',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (554,'SPACE WAGON',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (555,'BG-TRUCK',114)
Insert Into Modelo (Id, Nome, MarcaId) Values (556,'350Z',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (557,'ALTIMA',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (558,'AX',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (559,'D-21',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (560,'FRONTIER',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (562,'KING-CAB',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (563,'LIVINA',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (564,'MARCH',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (565,'MAXIMA',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (567,'MURANO',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (568,'NX',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (569,'PATHFINDER',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (571,'PRIMERA',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (572,'QUEST',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (573,'SENTRA',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (574,'STANZA',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (575,'180SX',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (576,'TERRANO',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (577,'TIIDA',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (578,'VERSA',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (579,'X-TRAIL',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (580,'XTERRA',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (581,'ZX',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (582,'106',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (583,'205',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (584,'206',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (585,'207',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (586,'3008',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (587,'306',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (588,'307',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (589,'308',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (590,'405',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (591,'406',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (592,'407',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (593,'408',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (594,'504',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (595,'505',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (596,'508',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (597,'605',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (598,'607',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (599,'806',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (600,'807',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (601,'BOXER',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (602,'HOGGAR',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (603,'PARTNER',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (604,'RCZ',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (605,'GRAN VOYAGER',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (606,'SUNDANCE',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (607,'TRANS-AM',69)
Insert Into Modelo (Id, Nome, MarcaId) Values (608,'TRANS-SPORT',69)
Insert Into Modelo (Id, Nome, MarcaId) Values (609,'911',70)
Insert Into Modelo (Id, Nome, MarcaId) Values (612,'BOXSTER',70)
Insert Into Modelo (Id, Nome, MarcaId) Values (613,'CAYENNE',70)
Insert Into Modelo (Id, Nome, MarcaId) Values (614,'CAYMAN',70)
Insert Into Modelo (Id, Nome, MarcaId) Values (615,'PANAMERA',70)
Insert Into Modelo (Id, Nome, MarcaId) Values (617,'21 SEDAN',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (618,'CLIO',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (619,'DUSTER',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (620,'EXPRESS',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (621,'FLUENCE',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (622,'KANGOO',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (623,'LAGUNA',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (624,'LOGAN',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (625,'MASTER',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (626,'MEGANE',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (627,'SAFRANE',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (628,'SANDERO',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (629,'SCENIC',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (630,'SYMBOL',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (631,'TRAFIC',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (632,'TWINGO',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (634,'9000',137)
Insert Into Modelo (Id, Nome, MarcaId) Values (635,'SL-2',162)
Insert Into Modelo (Id, Nome, MarcaId) Values (636,'CORDOBA',130)
Insert Into Modelo (Id, Nome, MarcaId) Values (637,'IBIZA',130)
Insert Into Modelo (Id, Nome, MarcaId) Values (638,'INCA',130)
Insert Into Modelo (Id, Nome, MarcaId) Values (641,'FORTWO',142)
Insert Into Modelo (Id, Nome, MarcaId) Values (642,'ACTYON SPORTS',21)
Insert Into Modelo (Id, Nome, MarcaId) Values (643,'CHAIRMAN',21)
Insert Into Modelo (Id, Nome, MarcaId) Values (644,'ISTANA',21)
Insert Into Modelo (Id, Nome, MarcaId) Values (645,'KORANDO',21)
Insert Into Modelo (Id, Nome, MarcaId) Values (646,'KYRON',21)
Insert Into Modelo (Id, Nome, MarcaId) Values (647,'MUSSO',21)
Insert Into Modelo (Id, Nome, MarcaId) Values (648,'REXTON',21)
Insert Into Modelo (Id, Nome, MarcaId) Values (649,'FORESTER',8)
Insert Into Modelo (Id, Nome, MarcaId) Values (650,'IMPREZA',8)
Insert Into Modelo (Id, Nome, MarcaId) Values (651,'LEGACY',8)
Insert Into Modelo (Id, Nome, MarcaId) Values (652,'OUTBACK',8)
Insert Into Modelo (Id, Nome, MarcaId) Values (653,'SVX',8)
Insert Into Modelo (Id, Nome, MarcaId) Values (654,'TRIBECA',8)
Insert Into Modelo (Id, Nome, MarcaId) Values (655,'VIVIO',8)
Insert Into Modelo (Id, Nome, MarcaId) Values (656,'BALENO',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (657,'GRAND VITARA',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (658,'IGNIS',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (660,'JIMNY',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (662,'SUPER CARRY',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (663,'SWIFT',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (664,'SX4',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (665,'VITARA',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (666,'WAGON R',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (667,'STARK',146)
Insert Into Modelo (Id, Nome, MarcaId) Values (668,'AVALON',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (669,'BANDEIRANTE',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (670,'CAMRY',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (671,'CELICA',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (672,'COROLLA',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (673,'CORONA',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (674,'HILUX',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (675,'LAND CRUISER',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (676,'MR-2',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (677,'PASEO',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (678,'PREVIA',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (679,'RAV4',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (680,'SUPRA',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (682,'PANTANAL',149)
Insert Into Modelo (Id, Nome, MarcaId) Values (684,'T-4',149)
Insert Into Modelo (Id, Nome, MarcaId) Values (685,'400 SERIES',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (687,'850',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (688,'900 SERIES',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (700,'AMAROK',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (701,'APOLLO',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (702,'BORA',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (703,'CARAVELLE',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (704,'CORRADO',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (706,'EOS',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (707,'EUROVAN',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (708,'FOX',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (709,'FUSCA',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (710,'GOL',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (711,'GOLF',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (713,'JETTA',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (714,'KOMBI',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (715,'LOGUS',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (717,'PARATI',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (718,'PASSAT',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (719,'POINTER',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (720,'POLO',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (722,'SANTANA',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (723,'SAVEIRO',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (725,'SPACEFOX',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (726,'TIGUAN',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (727,'TOUAREG',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (729,'VOYAGE',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (732,'ZDX',25)
Insert Into Modelo (Id, Nome, MarcaId) Values (737,'140',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (755,'BRASILIA',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (756,'BRASILVAN',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (775,'CORCEL',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (803,'PALIO WEEKEND',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (806,'FOCUS SEDAN',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (807,'FIESTA SEDAN',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (808,'FIESTA TRAIL',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (810,'207 SW',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (811,'ESCORT SW',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (812,'307 SEDAN',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (813,'307 SW',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (815,'C4 PALLAS',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (816,'C4 PICASSO',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (817,'C4 VTR',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (818,'CLIO SEDAN',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (819,'COROLLA FIELDER',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (824,'HILUX SW4',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (825,'MEGANE GRAND TOUR',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (827,'SANDERO STEPWAY',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (829,'XSARA PICASSO',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (1360,'COLHEITADEIRA',131)
Insert Into Modelo (Id, Nome, MarcaId) Values (1361,'PICKUP F75',158)
Insert Into Modelo (Id, Nome, MarcaId) Values (1362,'X12',17)
Insert Into Modelo (Id, Nome, MarcaId) Values (1365,'BEL AIR',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (1366,'RX',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (1369,'C-14',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (1370,'SRX4',155)
Insert Into Modelo (Id, Nome, MarcaId) Values (1372,'C-15',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (1373,'BRASIL',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (1377,'POLARA',18)
Insert Into Modelo (Id, Nome, MarcaId) Values (1380,'600',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (1382,'F-01',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (1383,'FALCON',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (1384,'GALAXIE',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (1386,'MAVERICK',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (1387,'MODELO A',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (1388,'NEW FIESTA',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (1389,'LINHA FX',82)
Insert Into Modelo (Id, Nome, MarcaId) Values (1391,'GTS',124)
Insert Into Modelo (Id, Nome, MarcaId) Values (1392,'H3',80)
Insert Into Modelo (Id, Nome, MarcaId) Values (1394,'PRIME',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (1395,'TIBURON',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (1397,'JEEP',87)
Insert Into Modelo (Id, Nome, MarcaId) Values (1398,'CJ5',87)
Insert Into Modelo (Id, Nome, MarcaId) Values (1399,'TC',239)
Insert Into Modelo (Id, Nome, MarcaId) Values (1404,'CLASSE CLC',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (1405,'CLASSE CLS',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (1408,'MONTEREY',110)
Insert Into Modelo (Id, Nome, MarcaId) Values (1411,'TOPSPORT',114)
Insert Into Modelo (Id, Nome, MarcaId) Values (1412,'TARGA',114)
Insert Into Modelo (Id, Nome, MarcaId) Values (1414,'X8',114)
Insert Into Modelo (Id, Nome, MarcaId) Values (1415,'370Z',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (1418,'GTB',124)
Insert Into Modelo (Id, Nome, MarcaId) Values (1419,'GTC',124)
Insert Into Modelo (Id, Nome, MarcaId) Values (1420,'GTE',124)
Insert Into Modelo (Id, Nome, MarcaId) Values (1421,'AUSTIN',115)
Insert Into Modelo (Id, Nome, MarcaId) Values (1423,'7TL',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (1424,'19',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (1426,'CONVERSÍVEL',175)
Insert Into Modelo (Id, Nome, MarcaId) Values (1427,'SUPERMINI',17)
Insert Into Modelo (Id, Nome, MarcaId) Values (1428,'TL',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (1429,'TOPOLINO',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (1430,'SR5',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (1431,'VITZ',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (1432,'VARIANT',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (1454,'CANDANGO',57)
Insert Into Modelo (Id, Nome, MarcaId) Values (1460,'SP2',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (1466,'RECORB',258)
Insert Into Modelo (Id, Nome, MarcaId) Values (1467,'POLAUTO',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (1508,'GORDINI',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (1509,'MINX',265)
Insert Into Modelo (Id, Nome, MarcaId) Values (1971,'ETIOS',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (1972,'ONIX',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (1973,'HB20',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (1975,'330',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (1976,'520',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (1978,'730',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (1980,'M1',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (1982,'SERIE Z',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (1983,'CLASSE SLK',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (1984,'CLASSE C',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (1985,'CLASSE E',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (1986,'CLASSE CL',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (1987,'CLASSE CLK',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (1988,'CLASSE S',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (1989,'CLASSE SL',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (1990,'CLASSE SLS',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (1991,'CLASSE G',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (1992,'CLASSE GL',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (1993,'CLASSE M',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (2032,'1500',288)
Insert Into Modelo (Id, Nome, MarcaId) Values (2061,'EQUUS',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (2067,'350 GT',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (2068,'400 GT',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (2069,'MIURA',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (2070,'ISLERO',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (2071,'ESPADA',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (2072,'COUNTACH',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (2073,'DIABLO',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (2074,'ZAGATO',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (2075,'ALAR',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (2076,'LM002',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (2077,'REVENTON',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (2078,'ANKONIAN',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (2080,'AVENTADOR',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (2081,'SESTO ELEMENTO',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (2082,'J3 TURIN',15)
Insert Into Modelo (Id, Nome, MarcaId) Values (2083,'J2',15)
Insert Into Modelo (Id, Nome, MarcaId) Values (2084,'SANDERO GT',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (2087,'SPIN',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2088,'TRAILBLAZER',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2097,'C3 PICASSO',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2098,'GRAND C4 PICASSO',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2099,'JUMPER MINIBUS',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2100,'JUMPER VETRATO',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2101,'207 SEDAN',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (2102,'207 QUIKSILVER',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (2103,'207 ESCAPADE',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (2104,'308 CC',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (2105,'BOXER PASSAGEIRO',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (2106,'NEW FIESTA SEDAN',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2108,'TRANSIT PASSAGEIRO',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2109,'TRANSIT CHASSI',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2110,'A4 AVANT',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2111,'S4 AVANT',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2112,'A5 SPORTBACK',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2113,'A5 CABRIOLET',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2114,'S5 COUPE',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2115,'S5 SPORTBACK',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2116,'S5 CABRIOLET',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2117,'A6 AVANT',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2118,'A6 ALLROAD',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2119,'S6 AVANT',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2120,'S7',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2121,'TT ROADSTER',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2122,'TT RS',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2123,'TT RS ROADSTER',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2124,'TTS ROADSTER',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2125,'R8 SPYDER',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2126,'R8 GT',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2127,'R8 GT SPYDER',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2129,'F12',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2130,'458 SPIDER',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2131,'458 ITALIA',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2132,'FF',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2133,'599',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2134,'SA',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2135,'CHALLENGE',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2136,'SUPERAMERICA',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2137,'F430 SPIDER',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2138,'430',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2139,'612 SESSANTA',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2140,'599 GTB',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2141,'SCUDERIA SPIDER',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2142,'512',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2143,'456 GT',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2144,'348 GTS',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2145,'348 SPIDER',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2146,'F355',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2147,'F355 SPIDER',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2148,'F50',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2149,'355 SPIDER',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2150,'360 MODENA',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2151,'PAJERO FULL',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (2152,'PAJERO DAKAR',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (2153,'PAJERO TR4',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (2154,'LANCER SPORTBACK',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (2155,'LANCER EVOLUTION',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (2156,'L200 TRITON SAVANA',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (2157,'L200 TRITON',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (2159,'LIVINA X-GEAR',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (2160,'GRAND LIVINA',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (2161,'NEW ACTYON SPORTS',21)
Insert Into Modelo (Id, Nome, MarcaId) Values (2162,'PRIUS',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (2163,'SPORT',114)
Insert Into Modelo (Id, Nome, MarcaId) Values (2164,'MTS',114)
Insert Into Modelo (Id, Nome, MarcaId) Values (2165,'SPIDER',114)
Insert Into Modelo (Id, Nome, MarcaId) Values (2166,'KABRIO',114)
Insert Into Modelo (Id, Nome, MarcaId) Values (2167,'SAGA',114)
Insert Into Modelo (Id, Nome, MarcaId) Values (2168,'SAGA II',114)
Insert Into Modelo (Id, Nome, MarcaId) Values (2169,'787',114)
Insert Into Modelo (Id, Nome, MarcaId) Values (2170,'X11',114)
Insert Into Modelo (Id, Nome, MarcaId) Values (2171,'GAIOLA',295)
Insert Into Modelo (Id, Nome, MarcaId) Values (2175,'NITRO',18)
Insert Into Modelo (Id, Nome, MarcaId) Values (2176,'CHALLENGER',18)
Insert Into Modelo (Id, Nome, MarcaId) Values (2177,'DART',18)
Insert Into Modelo (Id, Nome, MarcaId) Values (2178,'LE BARON',18)
Insert Into Modelo (Id, Nome, MarcaId) Values (2179,'CORDOBA',18)
Insert Into Modelo (Id, Nome, MarcaId) Values (2180,'CHARGER',18)
Insert Into Modelo (Id, Nome, MarcaId) Values (2181,'WINDSOR',19)
Insert Into Modelo (Id, Nome, MarcaId) Values (2183,'CROSSFIRE',19)
Insert Into Modelo (Id, Nome, MarcaId) Values (2184,'CORDOBA',19)
Insert Into Modelo (Id, Nome, MarcaId) Values (2185,'ESCALADE',155)
Insert Into Modelo (Id, Nome, MarcaId) Values (2186,'RIVIERA',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2187,'COUPE',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2188,'CENTURY',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2189,'APOLLO',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2190,'CENTURION',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2191,'EIGHT',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2192,'ELECTRA',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2193,'ESTATE WAGON',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2194,'GRAN SPORT',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2195,'GSX',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2196,'INVICTA',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2197,'LESABRE',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2198,'LIMITED',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2199,'PARK AVENUE',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2200,'RAINIER',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2201,'REATTA',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2202,'REGAL',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2203,'RENDEZVOUS',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2204,'ROADMASTER',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2205,'ROYAUM',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2206,'SKYHAWK',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2207,'SKYLARK',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2208,'SOMERSET',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2209,'SPECIAL',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2210,'SPORT WAGON',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2211,'SUPER',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2212,'TERRAZA',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2213,'WILDCAT',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2214,'LACROSSE',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2215,'ENCLAVE',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2217,'GL8',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2218,'HRV',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2219,'LUCERNE',41)
Insert Into Modelo (Id, Nome, MarcaId) Values (2230,'SIERRA',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2231,'BROUGHAM',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2232,'CHAIRMAN',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2233,'DAMAS',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2234,'GENTRA',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2235,'MAEPSY',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2236,'ISTANA',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2237,'KALOS',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2238,'KORANDO',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2239,'LACETTI',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2240,'LEMANS',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2242,'MATIZ',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2243,'MUSSO',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2244,'NEXIA',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2245,'REZZO',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2246,'ROYALE PRINCE',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2247,'ROYALE SALON',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2248,'STATESMAN',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2249,'TOSCA',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2250,'WINSTORM',51)
Insert Into Modelo (Id, Nome, MarcaId) Values (2252,'RURAL',158)
Insert Into Modelo (Id, Nome, MarcaId) Values (2253,'D100',18)
Insert Into Modelo (Id, Nome, MarcaId) Values (2259,'170',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (2261,'CUSTOM ROYAL',18)
Insert Into Modelo (Id, Nome, MarcaId) Values (2262,'CLUB COUPE',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2263,'MAGNUM',18)
Insert Into Modelo (Id, Nome, MarcaId) Values (2264,'GMC 100',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2265,'SOLSTICE',69)
Insert Into Modelo (Id, Nome, MarcaId) Values (2266,'ITAMARATY',158)
Insert Into Modelo (Id, Nome, MarcaId) Values (2267,'MARK V',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (2268,'GT',124)
Insert Into Modelo (Id, Nome, MarcaId) Values (2269,'CHAMPION',145)
Insert Into Modelo (Id, Nome, MarcaId) Values (2270,'BALILLA',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (2271,'INTERLAGOS',158)
Insert Into Modelo (Id, Nome, MarcaId) Values (2272,'X15',17)
Insert Into Modelo (Id, Nome, MarcaId) Values (2273,'F-85',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2274,'SPEEDSTER 356',70)
Insert Into Modelo (Id, Nome, MarcaId) Values (2275,'TOPIC FURGAO',88)
Insert Into Modelo (Id, Nome, MarcaId) Values (2276,'TOPIC ESCOLAR',88)
Insert Into Modelo (Id, Nome, MarcaId) Values (2279,'300D',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (2280,'CLASSE TE',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (2283,'T-100',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (2294,'MEGANE SEDAN',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (2295,'A4 CABRIOLET',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2298,'LINHA G',82)
Insert Into Modelo (Id, Nome, MarcaId) Values (2299,'LINHA G COUPE',82)
Insert Into Modelo (Id, Nome, MarcaId) Values (2300,'LINHA G CONVERSIVEL',82)
Insert Into Modelo (Id, Nome, MarcaId) Values (2301,'LINHA M',82)
Insert Into Modelo (Id, Nome, MarcaId) Values (2302,'LINHA EX',82)
Insert Into Modelo (Id, Nome, MarcaId) Values (2303,'LINHA JX',82)
Insert Into Modelo (Id, Nome, MarcaId) Values (2304,'LINHA QX',82)
Insert Into Modelo (Id, Nome, MarcaId) Values (2305,'MODELOS XF',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (2306,'F-TYPE',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (2307,'MARK VII',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (2308,'MARK VIII',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (2309,'MARK IX',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (2310,'MARK X',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (2311,'E-TYPE',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (2312,'C-TYPE',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (2313,'D-TYPE',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (2314,'MARK I',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (2315,'MARK II',86)
Insert Into Modelo (Id, Nome, MarcaId) Values (2346,'GT4R',124)
Insert Into Modelo (Id, Nome, MarcaId) Values (2347,'SPYDER',124)
Insert Into Modelo (Id, Nome, MarcaId) Values (2348,'GTI',124)
Insert Into Modelo (Id, Nome, MarcaId) Values (2349,'AM1',124)
Insert Into Modelo (Id, Nome, MarcaId) Values (2350,'AM2',124)
Insert Into Modelo (Id, Nome, MarcaId) Values (2351,'AM3',124)
Insert Into Modelo (Id, Nome, MarcaId) Values (2352,'AM4',124)
Insert Into Modelo (Id, Nome, MarcaId) Values (2353,'AMV',124)
Insert Into Modelo (Id, Nome, MarcaId) Values (2377,'ACTY',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2378,'AIRWAVE',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2379,'ASCOT',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2380,'BALLADE',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2381,'BEAT',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2382,'CR-X',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2383,'CONCERTO',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2384,'CR-Z',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2385,'DOMANI',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2386,'EDIX',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2387,'ELEMENT',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2388,'EV PLUS',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2389,'FCX',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2390,'FR-V',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2392,'HR-V',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2393,'HSC',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2394,'INSIGHT',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2396,'TL',25)
Insert Into Modelo (Id, Nome, MarcaId) Values (2397,'LIFE DUNK',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2398,'LOGO',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2399,'MOBILIO',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2400,'MDX',25)
Insert Into Modelo (Id, Nome, MarcaId) Values (2401,'ORTHIA',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2402,'PARTNER VAN',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2403,'PILOT',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2404,'RIDGELINE',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2405,'S2000',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2406,'S600',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2407,'S500',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2408,'S800',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2409,'STEPWGN',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2410,'STREAM',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2411,'THATS',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2412,'VAMOZ',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2413,'Z',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2414,'ZEST',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2441,'AERIO',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (2442,'ALTO',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (2443,'APV',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (2444,'KEI',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (2445,'LAPIN',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (2446,'MR WAGON',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (2447,'XL-7',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (2448,'VERONA',59)
Insert Into Modelo (Id, Nome, MarcaId) Values (2477,'JEEP CJ',158)
Insert Into Modelo (Id, Nome, MarcaId) Values (2479,'306 CABRIOLET',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (2484,'BELCAR',57)
Insert Into Modelo (Id, Nome, MarcaId) Values (2485,'M715',90)
Insert Into Modelo (Id, Nome, MarcaId) Values (2492,'407 SW',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (2493,'307 CC',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (2499,'STYLELINE',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2500,'ANGLIA',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2508,'GT2',26)
Insert Into Modelo (Id, Nome, MarcaId) Values (2509,'YUKON',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2510,'SPORTSMAN',54)
Insert Into Modelo (Id, Nome, MarcaId) Values (2514,'21 NEVADA',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (2515,'VEYRON',11)
Insert Into Modelo (Id, Nome, MarcaId) Values (2516,'ENZO',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2517,'306 SW',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (2528,'TI 80',28)
Insert Into Modelo (Id, Nome, MarcaId) Values (2532,'SPYDER 550',70)
Insert Into Modelo (Id, Nome, MarcaId) Values (2533,'380 GTB',10)
Insert Into Modelo (Id, Nome, MarcaId) Values (2534,'T-5',149)
Insert Into Modelo (Id, Nome, MarcaId) Values (2536,'KINGSWAY',18)
Insert Into Modelo (Id, Nome, MarcaId) Values (2537,'SSR',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2540,'IMPALA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2541,'208',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (2542,'GRAND BLAZER',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2555,'100 SERIES',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2558,'200 SERIES',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2559,'300 SERIES',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2561,'66',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2562,'700 SERIES',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2563,'AMAZON',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2564,'C303',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2566,'DUETT',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2567,'L3314',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2568,'OV 4',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2569,'P1800',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2570,'SUGGA',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2571,'TT',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2572,'ONCE',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2573,'DE LUXE',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2574,'CUSTOM',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2575,'T-BUCKET',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2576,'G15',17)
Insert Into Modelo (Id, Nome, MarcaId) Values (2588,'PAJERO FULL 3D',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (2589,'PAJERO SPORT',111)
Insert Into Modelo (Id, Nome, MarcaId) Values (2590,'120 CABRIO',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2591,'320 TOURING',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2592,'330 CABRIO',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2593,'SERIE 5 TOURING',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2594,'SERIE 6 CABRIO',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2595,'SERIE M CONVERSIVEL',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2596,'M5 TOURING',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2597,'SERIE Z ROADSTER',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2599,'KA SPORT',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2600,'CC',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (2605,'CERATO KOUP',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (2607,'ASTRO',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2608,'COROLLA XRS',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (2609,'ETIOS SEDAN',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (2611,'FREESTYLE',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2612,'COUGAR',110)
Insert Into Modelo (Id, Nome, MarcaId) Values (2615,'XUV 500',102)
Insert Into Modelo (Id, Nome, MarcaId) Values (2618,'XYLO',102)
Insert Into Modelo (Id, Nome, MarcaId) Values (2619,'BOLERO',102)
Insert Into Modelo (Id, Nome, MarcaId) Values (2620,'THAR',102)
Insert Into Modelo (Id, Nome, MarcaId) Values (2621,'AXE',102)
Insert Into Modelo (Id, Nome, MarcaId) Values (2622,'LEGEND',102)
Insert Into Modelo (Id, Nome, MarcaId) Values (2623,'CJ3',87)
Insert Into Modelo (Id, Nome, MarcaId) Values (2624,'ARMADA',102)
Insert Into Modelo (Id, Nome, MarcaId) Values (2625,'CHASSI',102)
Insert Into Modelo (Id, Nome, MarcaId) Values (2626,'SCORPIO PICK-UP',102)
Insert Into Modelo (Id, Nome, MarcaId) Values (2627,'STAR TRUCK',6)
Insert Into Modelo (Id, Nome, MarcaId) Values (2628,'STAR',6)
Insert Into Modelo (Id, Nome, MarcaId) Values (2629,'STAR VAN CARGO',6)
Insert Into Modelo (Id, Nome, MarcaId) Values (2630,'STAR VAN PASSAGEIROS',6)
Insert Into Modelo (Id, Nome, MarcaId) Values (2632,'ALVORADA',141)
Insert Into Modelo (Id, Nome, MarcaId) Values (2633,'CHAMBORD',141)
Insert Into Modelo (Id, Nome, MarcaId) Values (2637,'PROFISSIONAL',141)
Insert Into Modelo (Id, Nome, MarcaId) Values (2639,'VEDETTE',141)
Insert Into Modelo (Id, Nome, MarcaId) Values (2640,'ARONDE',141)
Insert Into Modelo (Id, Nome, MarcaId) Values (2641,'1200S',141)
Insert Into Modelo (Id, Nome, MarcaId) Values (2642,'1000',141)
Insert Into Modelo (Id, Nome, MarcaId) Values (2645,'HB20X',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (2646,'HB20S',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (2648,'MONZA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2649,'CHEVETTE',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2650,'X60',98)
Insert Into Modelo (Id, Nome, MarcaId) Values (2651,'TRAX',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2652,'118',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2653,'120',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2654,'130',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2655,'BAVARIA',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2656,'C-2800',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2657,'318',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2658,'320',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2659,'318 CABRIO',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2660,'325 CABRIO',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2661,'530',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2662,'540',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2663,'550',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2664,'740',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2665,'750',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2666,'760',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2675,'MATRIX 4X4',341)
Insert Into Modelo (Id, Nome, MarcaId) Values (2694,'A7',132)
Insert Into Modelo (Id, Nome, MarcaId) Values (2695,'A9',132)
Insert Into Modelo (Id, Nome, MarcaId) Values (2696,'A9 CARGO',132)
Insert Into Modelo (Id, Nome, MarcaId) Values (2697,'T20',132)
Insert Into Modelo (Id, Nome, MarcaId) Values (2698,'T20 BAU',132)
Insert Into Modelo (Id, Nome, MarcaId) Values (2699,'T22',132)
Insert Into Modelo (Id, Nome, MarcaId) Values (2704,'SUPER 90 COUPE',64)
Insert Into Modelo (Id, Nome, MarcaId) Values (2705,'X20',17)
Insert Into Modelo (Id, Nome, MarcaId) Values (2706,'ITAIPU',17)
Insert Into Modelo (Id, Nome, MarcaId) Values (2707,'G800',17)
Insert Into Modelo (Id, Nome, MarcaId) Values (2708,'XEF',17)
Insert Into Modelo (Id, Nome, MarcaId) Values (2709,'MOTOMACHINE',17)
Insert Into Modelo (Id, Nome, MarcaId) Values (2710,'BUGATO',17)
Insert Into Modelo (Id, Nome, MarcaId) Values (2711,'QT',17)
Insert Into Modelo (Id, Nome, MarcaId) Values (2716,'CAICARA',57)
Insert Into Modelo (Id, Nome, MarcaId) Values (2717,'CARCARA',57)
Insert Into Modelo (Id, Nome, MarcaId) Values (2718,'FISSORE',57)
Insert Into Modelo (Id, Nome, MarcaId) Values (2719,'MALZONI',57)
Insert Into Modelo (Id, Nome, MarcaId) Values (2720,'VEMAGUET',57)
Insert Into Modelo (Id, Nome, MarcaId) Values (2727,'C4 LOUNGE',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2728,'CX-7',108)
Insert Into Modelo (Id, Nome, MarcaId) Values (2729,'TR',147)
Insert Into Modelo (Id, Nome, MarcaId) Values (2730,'LUCENA',147)
Insert Into Modelo (Id, Nome, MarcaId) Values (2731,'SEVETSE',147)
Insert Into Modelo (Id, Nome, MarcaId) Values (2732,'RAGGE',147)
Insert Into Modelo (Id, Nome, MarcaId) Values (2733,'C70',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2734,'C30',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2735,'544',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2736,'S40',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2737,'S60',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2738,'S70',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2739,'S80',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2740,'V40',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2741,'V50',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2742,'V60',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2743,'V70',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2744,'S90',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2745,'XC60',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2746,'XC70',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2747,'XC90',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2748,'P1900',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2749,'PV36',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2750,'PV444',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2751,'PV544',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2752,'PV51',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2753,'PV654',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2754,'C50',53)
Insert Into Modelo (Id, Nome, MarcaId) Values (2755,'190',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (2756,'CLASSE CLA',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (2757,'CLASSE V',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (2758,'VANEO',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (2759,'CITAN',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (2760,'VARIO',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (2761,'CLASSE S CLASSICO',4)
Insert Into Modelo (Id, Nome, MarcaId) Values (2809,'J3S',15)
Insert Into Modelo (Id, Nome, MarcaId) Values (2810,'PICK-UP',345)
Insert Into Modelo (Id, Nome, MarcaId) Values (2811,'VAN',345)
Insert Into Modelo (Id, Nome, MarcaId) Values (2823,'C3 SOLARIS',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2824,'C3 XTR',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2825,'C4 SOLARIS',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2826,'C5 BREAK/TOURER',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2827,'XSARA BREAK',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2828,'XSARA VTS',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2829,'XANTIA BREAK',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2830,'XM BREAK',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2831,'C15',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2832,'NEMO',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2833,'VISA',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2834,'C1',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2835,'C2',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2836,'C3 PLURIEL',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2837,'DS4',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2838,'DS5',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2839,'JUMPY',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2840,'C-CROSSER',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2841,'C35',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2842,'C25',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2843,'CX',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2844,'CX BREAK',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2845,'AXEL',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2846,'DYANE',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2847,'GS/GSA',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2848,'GS/GSA BREAK',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2849,'MEHARI',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2850,'SAXO',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2851,'SM',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2852,'ELYSEE',5)
Insert Into Modelo (Id, Nome, MarcaId) Values (2853,'MASTER MINIBUS',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (2854,'CELER',47)
Insert Into Modelo (Id, Nome, MarcaId) Values (2855,'CELER SEDAN',47)
Insert Into Modelo (Id, Nome, MarcaId) Values (2856,'CIELO SEDAN',47)
Insert Into Modelo (Id, Nome, MarcaId) Values (2857,'A1 SPORTBACK',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2858,'A1 QUATTRO',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2859,'A3 SPORTBACK',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2860,'RS4 AVANT',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2861,'A8L W12',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2862,'R8 V10',32)
Insert Into Modelo (Id, Nome, MarcaId) Values (2863,'RANGER CD',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2864,'T140',15)
Insert Into Modelo (Id, Nome, MarcaId) Values (2865,'X1',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2866,'X3',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2867,'X5',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2868,'X6',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2869,'840',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2870,'850',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2871,'645',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2872,'650',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (2874,'FIT TWIST',7)
Insert Into Modelo (Id, Nome, MarcaId) Values (2876,'MP4',346)
Insert Into Modelo (Id, Nome, MarcaId) Values (2877,'F1',346)
Insert Into Modelo (Id, Nome, MarcaId) Values (2878,'MONDEO SW',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2879,'ESCORT SEDAN',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2880,'ESCORT CONVERSIVEL',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2881,'MX-6',108)
Insert Into Modelo (Id, Nome, MarcaId) Values (2884,'CORISCO',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2885,'CHEVELLE',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2886,'EXCURSION',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2887,'TOURAN',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (2890,'F-10000',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2891,'HOGGAR ESCAPADE',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (2901,'PHAETON',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2913,'TRANSPORTER',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (2914,'GRAND BESTA',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (2915,'200SX',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (2916,'240SX',43)
Insert Into Modelo (Id, Nome, MarcaId) Values (2921,'300M',19)
Insert Into Modelo (Id, Nome, MarcaId) Values (2922,'300C TOURING',19)
Insert Into Modelo (Id, Nome, MarcaId) Values (2928,'TORINO',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2931,'VENTURE',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2932,'FLEETLINE',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2933,'FLEETMASTER',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2934,'DELUXE',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2936,'ESCORT XR3',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (2937,'MASTER',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (2938,'TORONADO',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2939,'SIX',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2940,'EIGHT',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2941,'DELUXE',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2942,'SERIES 60',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2943,'SERIES 70',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2944,'SERIES 80',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2945,'SERIES 90',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2946,'STARFIRE',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2947,'442',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2948,'CUTLASS',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2949,'CUTLASS SUPREME',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2950,'CUTLASS SALON',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2951,'CUTLASS CALAIS',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2952,'CUTLASS CIERA',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2953,'CUSTOM CRUISER',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2954,'VISTA CRUISER',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2955,'F-85',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2957,'FIRENZA',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2958,'ACHIEVA',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2959,'ALERO',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2960,'AURORA',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2961,'BRAVADA',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2962,'INTRIGUE',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2963,'SILHOUETTE',120)
Insert Into Modelo (Id, Nome, MarcaId) Values (2972,'SUPERBIRD',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2973,'FURY',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2974,'SPECIAL',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2975,'PROWLER',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2976,'TRAIL DUSTER',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2977,'VOYAGER',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2978,'SCAMP',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2979,'ARROW',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2980,'PT50',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2981,'PT57',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2982,'PT81',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2983,'PT105',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2984,'PT125',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2985,'EXPRESS',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2986,'VOYAGER EXPRESSO',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2987,'NEON',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2988,'LASER',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2989,'CARAVELLE',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2990,'STATION WAGON',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2991,'MODEL Q',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2992,'MODEL P6',123)
Insert Into Modelo (Id, Nome, MarcaId) Values (2993,'DB9 COUPE',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (2994,'DB9 VOLANTE',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (2995,'VIRAGE COUPE',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (2996,'RAPIDE S',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (2997,'V12 VANTAGE',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (2998,'V8 VANTAGE COUPE',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (2999,'V8 VANTAGE ROADSTER',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (3000,'V8 VANTAGE S COUPE',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (3001,'V8 VANTAGE S ROADSTER',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (3002,'VANQUISH COUPE',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (3003,'VANQUISH VOLANTE',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (3004,'V12 ZAGATO',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (3005,'DB5',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (3007,'DBS',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (3008,'DBS VOLANTE',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (3009,'CYGNET',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (3010,'ONE-77',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (3011,'DBR9',31)
Insert Into Modelo (Id, Nome, MarcaId) Values (3013,'M3',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (3014,'M5',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (3015,'M6',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (3016,'X6 M',36)
Insert Into Modelo (Id, Nome, MarcaId) Values (3017,'CABRIO',113)
Insert Into Modelo (Id, Nome, MarcaId) Values (3018,'COUPE',113)
Insert Into Modelo (Id, Nome, MarcaId) Values (3019,'ROADSTER',113)
Insert Into Modelo (Id, Nome, MarcaId) Values (3020,'COUNTRYMAN',113)
Insert Into Modelo (Id, Nome, MarcaId) Values (3021,'PACEMAN',113)
Insert Into Modelo (Id, Nome, MarcaId) Values (3022,'JOHN COOPER WORKS',113)
Insert Into Modelo (Id, Nome, MarcaId) Values (3023,'ZONDA',122)
Insert Into Modelo (Id, Nome, MarcaId) Values (3024,'NEW XV',8)
Insert Into Modelo (Id, Nome, MarcaId) Values (3025,'IMPREZA WRX HATCH',8)
Insert Into Modelo (Id, Nome, MarcaId) Values (3026,'IMPREZA WRX STI HATCH',8)
Insert Into Modelo (Id, Nome, MarcaId) Values (3027,'IMPREZA WRX STI SEDAN',8)
Insert Into Modelo (Id, Nome, MarcaId) Values (3028,'IMPREZA WRX SEDAN',8)
Insert Into Modelo (Id, Nome, MarcaId) Values (3030,'ETIOS CROSS',23)
Insert Into Modelo (Id, Nome, MarcaId) Values (3031,'HURACAN',12)
Insert Into Modelo (Id, Nome, MarcaId) Values (3032,'UP',2)
--Insert Into Modelo (Id, Nome, MarcaId) Values (3080,'EXPLORER',195)
Insert Into Modelo (Id, Nome, MarcaId) Values (4964,'FORTWO CABRIO',142)
Insert Into Modelo (Id, Nome, MarcaId) Values (4969,'GT',26)
Insert Into Modelo (Id, Nome, MarcaId) Values (4970,'GTL',26)
Insert Into Modelo (Id, Nome, MarcaId) Values (4971,'GTM',26)
Insert Into Modelo (Id, Nome, MarcaId) Values (4972,'C2',26)
Insert Into Modelo (Id, Nome, MarcaId) Values (4973,'CRX',26)
Insert Into Modelo (Id, Nome, MarcaId) Values (4974,'AC 2000',26)
Insert Into Modelo (Id, Nome, MarcaId) Values (4975,'AVIATOR',99)
Insert Into Modelo (Id, Nome, MarcaId) Values (4976,'BLACKWOOD',99)
Insert Into Modelo (Id, Nome, MarcaId) Values (4977,'CAPRI',99)
Insert Into Modelo (Id, Nome, MarcaId) Values (4978,'CONTINENTAL',99)
Insert Into Modelo (Id, Nome, MarcaId) Values (4979,'LS',99)
Insert Into Modelo (Id, Nome, MarcaId) Values (4980,'MARK',99)
Insert Into Modelo (Id, Nome, MarcaId) Values (4981,'MARK LT',99)
Insert Into Modelo (Id, Nome, MarcaId) Values (4982,'MKR',99)
Insert Into Modelo (Id, Nome, MarcaId) Values (4983,'MKS',99)
Insert Into Modelo (Id, Nome, MarcaId) Values (4984,'MKX',99)
Insert Into Modelo (Id, Nome, MarcaId) Values (4985,'MKZ',99)
Insert Into Modelo (Id, Nome, MarcaId) Values (4986,'NAVIGATOR',99)
Insert Into Modelo (Id, Nome, MarcaId) Values (4987,'PREMIERE',99)
Insert Into Modelo (Id, Nome, MarcaId) Values (4988,'TOWN CAR',99)
Insert Into Modelo (Id, Nome, MarcaId) Values (4989,'VERSAILLES',99)
Insert Into Modelo (Id, Nome, MarcaId) Values (4990,'ZEPHYR',99)
Insert Into Modelo (Id, Nome, MarcaId) Values (4991,'CLASSIC',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (4992,'ACTYON',21)
Insert Into Modelo (Id, Nome, MarcaId) Values (5003,'MARAJO',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (5004,'SUPREMA',1)
Insert Into Modelo (Id, Nome, MarcaId) Values (5005,'NEW BEETLE',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (5006,'QUANTUM',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (5007,'CROSSFOX',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (5008,'MILLE',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (5009,'GC2',534)
Insert Into Modelo (Id, Nome, MarcaId) Values (5010,'EC7',534)
Insert Into Modelo (Id, Nome, MarcaId) Values (5011,'530',98)
Insert Into Modelo (Id, Nome, MarcaId) Values (5012,'MOBI',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (5013,'TORO',3)
Insert Into Modelo (Id, Nome, MarcaId) Values (5014,'RENEGADE',87)
Insert Into Modelo (Id, Nome, MarcaId) Values (5015,'DUSTER OROCH',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (5016,'SANDERO RS',24)
Insert Into Modelo (Id, Nome, MarcaId) Values (5017,'HB20R',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (5018,'GRAND SANTA FE',14)
Insert Into Modelo (Id, Nome, MarcaId) Values (5019,'GOLF VARIANT',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (5020,'SPACE CROSS',2)
Insert Into Modelo (Id, Nome, MarcaId) Values (5021,'2008',22)
Insert Into Modelo (Id, Nome, MarcaId) Values (5022,'QUORIS',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (5023,'GRAND CARNIVAL',16)
Insert Into Modelo (Id, Nome, MarcaId) Values (5024,'T8',15)
Insert Into Modelo (Id, Nome, MarcaId) Values (5025,'T6',15)
Insert Into Modelo (Id, Nome, MarcaId) Values (5026,'T5',15)
Insert Into Modelo (Id, Nome, MarcaId) Values (5027,'KA SEDAN',13)
Insert Into Modelo (Id, Nome, MarcaId) Values (5028,'FOCUS FASTBACK',13)

--ATIVAR IDENTITY TABELA
SET IDENTITY_INSERT Modelo OFF